#pragma once

#include <memory>
#include <iostream>
#include <vector>
#include <string>
#include <unordered_map>
#include <thread>
#include <mutex>
#include <algorithm>
#include <filesystem>
#include <d3d11.h>
#include <dxgi.h>
#include <xmmintrin.h>
#include <Windows.h>
#include <lazy_importer.hpp>
#include <fnv1a.hpp>
#include <hash.hpp>
#include <syscall.hpp>
#include <xor.hpp>